### ISSUE TITLE
ut-core-4.5.0: Building Weak Skeletons & use DLOpen for strong

### ISSUE THREAD

**Issue by Ulrond** [rdkcentral/ut-core#14]
# Build Skeleton Library

This will make inputting files into the ut-core simple.

Change the makefile, so that SKELETON_SRC is build into a seperate library in UT-CORE makefiles, so no other dependencies area required.

It should detect if the image is already there, and not build it again, so to rebuild the library you could have to perform a clean.

It's up-to the caller, to replace the library with the target one in question as required, this can be done by copying the library in the lib directory, or by not copying it to the final target ,and using the one from rootfs or LD_LIBRARY_PATH

* **Requirement would be that ideally the SKELETON_SRC by default should be weak.** - Change the autogeneratioin to make the functions weak by default.

## Goals

- Create Stubs as Weak
- Include the SKELETON_SRC as part of the ut-core build in both linux + arm building.
- May need to separate as a SKELETON_SRC

**Comment by kanjoe24** [comment]
Need to triage it first.

**Comment by Ulrond** [comment]
Rejected as not required due to AIDL
