### ISSUE TITLE
Autogen Scripts Enhancement/Bug

### ISSUE THREAD

**Issue by saniya-09** [rdkcentral/ut-core#17]
Autogen script requires below enhancements/fix :

1. Dependent packages were not documented, hence direct script executions were failing
2. Autogenerate script exits abruptly on any failure, without any failure/error notification on console. (even with export AGT_DEBUG=1)
3. The -c option to delete workspace is not working
4. Script exits abruptly in autogenerate_skeletons.sh, at a function which uses ruby(when ruby is not pre-installed). Even on installing ruby, re-run of script doesn’t work. We had to manually delete the workspace folder(-c not working)
5. UT repo url prompted by the script was not correct.
6. AGT_DOXY_REPO variable value in autogenerate.sh script is pointing to incorrect Doxygen repo.

**Comment by Ulrond** [comment]
5. UT repo url prompted by the script was not correct. -> Will be fixed by #5
