### ISSUE TITLE
ut-kvp - test support for enumerated list

### ISSUE THREAD

**Issue by Ulrond** [rdkcentral/ut-core#34]
We need to ensure that we support enumerated lists and maybe have a getListFunction for kvp.

```c
getListCount("established_timings");
getListElement(char *key, int32_t index);
```

```yaml
    established_timings:
      - 720x400@70Hz
      - 800x600@60Hz
 ```

- Need to also write tests to support the change

**Comment by srinivasgtl** [comment]
Audio Test profile with enumerated.  Please check with this profile yml file as well.
https://github.com/rdkcentral/rdk-halif-test-device_settings/blob/feature/issues14_dsVideoPort_TestSpec/profiles/include/Panel_4K_VideoPort.yaml

**Comment by kanjoe24** [comment]
getListElement(char *key, int32_t index); -> Is not required

you can already access elements of the list by

```c
ut_kvp_getUInt32Field( <instance>, "a/b/<elemment>" );
```

**Comment by kanjoe24** [comment]
getListCount("a/b/list");
