### ISSUE TITLE
i53: ut-core: add docker run instructions for the arm toolchain sc docker launch instructions for the 

### ISSUE THREAD

**Issue by Ulrond** [rdkcentral/ut-core#53]
# RDK Dunfell Docker Toolchain Manual

This manual guides you through the process of using the RDK Dunfell Docker Toolchain to build projects targeted for ARM architecture, using Docker.

## Launching the Toolchain Docker Container

To start the Docker container and open a bash shell within it, use the following command:

```bash
sc docker run rdk-dunfell-toolchain /bin/bash
```

## Setting Up the Environment

Once inside the Docker container, follow these steps to set up the environment:

1. Navigate to the toolchain directory:

    ```bash
    cd /opt/toolchains/rdk-glibc-arm-toolchain/
    ```

2. Activate the environment setup for ARMv7:

    ```bash
    . environment-setup-armv7at2hf-neon-oe-linux-gnueabi
    ```

3. To verify that the compiler (`CC`) is set correctly in the environment, execute:

    ```bash
    echo $CC
    ```

    The output should start with `arm-oe-linux-gnueabi-gcc` followed by various compiler switches.

## Building the Project

To build your project using the ARM toolchain, follow these steps:

1. Change to your project directory (replace `<project>` with your actual project directory name):

    ```bash
    cd <project>
    ```

2. Start the build process by specifying the target:

    ```bash
    make TARGET=arm
    ```

## Optional Single Command Execution

Alternatively, you can combine all the steps into a single command to set up the environment and build your project directly. Here’s how:

```bash
sc docker run rdk-dunfell-toolchain "/bin/bash -c '. /opt/toolchains/rdk-glibc-arm-toolchain/environment-setup-armv7at2hf-neon-oe-linux-gnueabi; cd <project>; make TARGET=arm'"
```

Make sure to replace `<project>` with your actual project directory. This command facilitates running everything in one go inside the Docker container.

**Comment by kanjoe24** [comment]
created wiki: https://github.com/rdkcentral/ut-core/wiki/RDK-Dunfell-Docker-Toolchain-Manual
