### ISSUE TITLE
i73: ut_core: Enchanced release script to support automated release testing

### ISSUE THREAD

**Issue by Ulrond** [rdkcentral/ut-core#73]
Requirement to support testing for releases

- TARGET=linux
- TARGET=arm
- building the testing suites & running them checking for errors, for all framework & ut-core functions.
- clone halif header and trigger cloning of ut-core & framework
- run ut test from halif to ensure backwards comaptbility.

- ut-core - is on a fixed version of ut-control, so that changes to ut-control will not break ut-core
- ut-core - is auto ingested by all halif testing suites on minor changes
- ut-core - major change will not be auto-ingested, but will be signal during the compile time, to request a please upgrade, this basically is stating that the latest version of ut-core requires changes to the halif-testing suites to support it. ( Should be used where the API is not longer backwards compatible, or theres a risk to breaking the halif-tests).

**Comment by kanjoe24** [comment]
|ENV|CMAKE(Host)|CURL(Target)|OPENSSL(Target)|
|----|--------|------|---------|
|Ubuntu+build essentials|NO|YES|NO
|VM-SYNC|YES|YES|YES
|RDK-DUNFELL(arm)|NO|YES|YES
