### ISSUE TITLE
ut_core 2.2.0: build clean is not removing all obj, library files

### ISSUE THREAD

**Issue by bhanucbp** [rdkcentral/ut-core#75]
ut_core version: 2.2.0
issue:The /build.sh clean script used in the HAL test isn't removing object files and libraries generated in ut-core/framework/ut-control/obj/framework/. When switching compilers, the existing object files might not be compatible with the new compiler, leading to the error "file not recognized: file format not recognized".

**Comment by kanjoe24** [comment]
Hi Bhanu,
On checking the build.sh and Makefile of ut/ , realised that its not propagaing the request to ut-core.
Please find the changes
```
@rdk-dunfell ut (main)$ git diff
diff --git a/Makefile b/Makefile
index 9c01659..dfe3e72 100644
--- a/Makefile
+++ b/Makefile
@@ -87,3 +87,7 @@ list:
 clean:
        @echo UT [$@]
        make -C ./ut-core clean
+
+cleanall:
+       @echo UT [$@]
+       make -C ./ut-core cleanall
diff --git a/build.sh b/build.sh
index d6ac8e4..1588264 100755
--- a/build.sh
+++ b/build.sh
@@ -60,7 +60,7 @@ else
     check_next_revision
     cd ./ut-core
     git checkout ${UT_CORE_PROJECT_VERSION}
-    ./build.sh
+    ./build.sh $@
     cd ..
     ./${0} $@
 fi
@rdk-dunfell ut (main)$ 
@rdk-dunfell ut (main)$ git remote -vv
origin	git@github.com:rdkcentral/rdk-halif-test-power_manager.git (fetch)
origin	git@github.com:rdkcentral/rdk-halif-test-power_manager.git (push)
```

With these changes it works as expected. But the repo is hal interface test. I am not sure, who is in-charge of bringing in changes to this repo.
@Ulrond / @bhanucbp , can you please confirm?

Regards
Jyotsna

**Comment by Ulrond** [comment]
this is a problem with the testing suite not actually ut-core, the testing suite's build script needs to be upgraded.. We should have released this ut-core change as a major, so that engineers where aware of a change required..

So outside of the scope of ut-core, each testing suite will have to be upgraded as per the details above.
