### ISSUE TITLE
Clean all the shared objects and executable created during cleanall

### ISSUE THREAD

**Issue by srinivasgtl** [rdkcentral/ut-core#81]
While "cleanall", We need to create all the binaries, libraries etc created during the build.

Add the following commands during clean in the ut-core Makefile.
        @$(RM) -rf $(BIN_DIR)/*.so*
        @$(RM) -rf $(BIN_DIR)/*.a
        @$(RM) -rf $(BIN_DIR)/$(TARGET_EXEC)

Thanks.

**Comment by kanjoe24** [comment]
Just a thought, can this be handled by HALIF-test Makefile?

**Comment by Ulrond** [comment]
the idea being that cleanall deletes all the libraries when you swap between linux/arm, where as clean should be used to delete your currently build objects.
