### ISSUE TITLE
i88:ut_core: Updated the templates with Control Plane & Emulator Requirements

### ISSUE THREAD

**Issue by Ulrond** [rdkcentral/ut-core#88]
@Ulrond  needs to update these sections wiht some data

```
### Emulator Requirements-abc test functionality

### Control Plane Requirements-abc test functionality
```

_Originally posted by @Ulrond in https://github.com/rdkcentral/ut-core/pull/57#discussion_r1610176563_

**Comment by kanjoe24** [comment]
No longer required. Closing this ticket.
